# Jonathan Halverson
# Wednesday, November 29, 2017
# Into to recurrent neural networks

In [3]:
import tensorflow as tf

In [1]:
n_inputs = 3
n_neurons = 5

In [4]:
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

In [5]:
Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons],dtype=tf.float32))

In [6]:
Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

In [7]:
init = tf.global_variables_initializer()

In [8]:
import numpy as np

X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t=0
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t=1

In [9]:
with tf.Session() as sess:
     init.run()
     Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0:X0_batch, X1:X1_batch})

In [10]:
print(Y0_val) # output t=0

[[ 0.99306381  0.99298626 -0.99782985 -0.25774899 -0.30837062]
 [ 1.          0.99817121 -1.         -0.93925476 -0.06077835]
 [ 1.          0.99952406 -1.         -0.99668026  0.1945263 ]
 [ 1.         -1.         -0.99673599  0.9874301   0.99999547]]


In [11]:
print(Y1_val) # output t=1

[[ 1.         -0.89035678 -1.         -0.99998116  0.99817199]
 [ 0.83015853 -0.83369333 -0.70955974 -0.97313374  0.97137022]
 [ 1.         -0.98957849 -1.         -0.99984014  0.99090534]
 [ 0.99999607  0.89987296  0.33330345  0.52346897  0.86653197]]
