# Jonathan Halverson
# Tuesday, November 14, 2017
# Simple calculations with TF

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
import os
# supress tensorflow logging other than errors
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [3]:
print(tf.__version__)

1.1.0


In [4]:
tf.reset_default_graph()

In [5]:
x = range(10)
y = range(10, 20)

In [6]:
X = tf.constant(x, dtype=tf.float32, name='X')
Y = tf.constant(y, dtype=tf.float32, name='Y')

In [7]:
Z = tf.constant(3, dtype=tf.float32)
Z

<tf.Tensor 'Const:0' shape=() dtype=float32>

In [9]:
H = tf.constant([3], dtype=tf.float32)
H

<tf.Tensor 'Const_1:0' shape=(1,) dtype=float32>

In [10]:
K = X + Z

In [11]:
max_element = tf.maximum(X, Y)

In [12]:
mean_X = tf.reduce_mean(X)
mean_Y, mean_Y_op = tf.metrics.mean(Y)

In [15]:
mse, mse_op = tf.metrics.mean_squared_error(X, Y)
mse_manual = tf.reduce_mean(tf.square(X - Y))
mse_loss = tf.losses.mean_squared_error(labels=X, predictions=Y)

In [16]:
init = tf.global_variables_initializer()

In [18]:
with tf.Session() as s:
     init.run()
     s.run(tf.local_variables_initializer())
     v = s.run([mean_Y, mean_Y_op])

     print mean_X.eval()
     print max_element.eval()
     print K.eval()
     print v[1]
     print mean_Y_op.eval()
     print mse_op.eval(), mse_manual.eval(), mse_loss.eval()

4.5
[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
[  3.   4.   5.   6.   7.   8.   9.  10.  11.  12.]
14.5
14.5
100.0 100.0
100.0


### tf.squeeze

In [29]:
tf.reset_default_graph()

In [30]:
X = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]), dtype=tf.float32)
output = tf.layers.dense(X, units=1, activation=None, name='hidden1')
sq = tf.squeeze(output, 1)

In [31]:
init = tf.global_variables_initializer()

In [32]:
with tf.Session() as sess:
     init.run()
     print output.eval()
     print sq.eval()

[[-2.82090831]
 [-8.37100124]]
[-2.82090831 -8.37100124]
