# Jonathan Halverson
# Wednesday, November 8, 2017
# Simple check of a single layer

The goal here is demonstrate an understanding of the tf.layers.dense function. By initializing the kernel and bias in a controlled way, the output can be calculated and confirmed.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
n_records = 3
n_inputs = 10
n_neurons = 6

In [3]:
tf.reset_default_graph()

Create an array of records (rows corresponds to records while columns to features):

In [4]:
#X_np = 1 * np.ones(n_records * n_inputs).reshape(n_records, n_inputs)
X_np = np.array([n_inputs * [1], n_inputs * [2], n_inputs * [3]], dtype=np.float32)
#X_np = np.random.randint(10, size=(n_records, n_inputs)).astype(dtype=np.float32)
X_np

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]], dtype=float32)

Convert this from a numpy array to a tensorflow tensor:

In [5]:
X = tf.constant(X_np, tf.float32, name="X")
X

<tf.Tensor 'X:0' shape=(3, 10) dtype=float32>

In [6]:
X.get_shape(), X.dtype, X.name

(TensorShape([Dimension(3), Dimension(10)]), tf.float32, u'X:0')

The kernel_initializer parameter in tf.layers.dense must be set to an initializer. We have not found a way to set it equal to a modified numpy array.

In [7]:
w = tf.ones_initializer(dtype=tf.float32)
b = tf.ones_initializer(dtype=tf.float32)

In [8]:
hidden1 = tf.layers.dense(inputs=X, units=n_neurons, kernel_initializer=w,
                          bias_initializer=b, activation=None, name='hidden1')

In [9]:
init = tf.global_variables_initializer()

In [10]:
with tf.Session() as sess:
     init.run()
     print hidden1.eval()

[[ 11.  11.  11.  11.  11.  11.]
 [ 21.  21.  21.  21.  21.  21.]
 [ 31.  31.  31.  31.  31.  31.]]


We see that the neurons in the layer are outputting the correct values. One can change the records in the X_np array or the activation function to test other cases.

Here are other choices for the initialization of the kernel (i.e., weights):

In [11]:
from tensorflow.python.ops.init_ops import glorot_uniform_initializer

In [12]:
glorot_uniform_initializer()

In [13]:
tf.contrib.layers.xavier_initializer(uniform=True, seed=None, dtype=tf.float32)

<function tensorflow.contrib.layers.python.layers.initializers._initializer>

In [14]:
tf.truncated_normal_initializer(stddev=0.01)